import { useCallback, useEffect, useMemo, useState } from "react";
import { open, save } from "@tauri-apps/plugin-dialog";
import { flexRender, getCoreRowModel, useReactTable, type ColumnDef } from "@tanstack/react-table";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { CircleDollarSign, Eye, EyeOff, FileDown, FileInput, Landmark, Plus, RefreshCw, TrendingDown, TrendingUp } from "lucide-react";
import type { AppSettings, Holding, ImportReport, Instrument, InvestmentAccount, PortfolioSnapshot, PortfolioTransaction, QuoteRefreshReport, SearchResult } from "../types";
import { call, WorkbenchError } from "../lib/api";
import { useSearchTarget } from "../lib/useSearchTarget";
import { useMutation } from "../lib/useMutation";
import { emptyAccount, emptyInstrument, emptyTransaction } from "../lib/defaults";
import { money, multiplyDecimals, number } from "../lib/format";
import { Badge, Button, Card, EmptyState, ErrorBanner, Field, Input, Modal, SectionHeader, Select, Textarea } from "../components/ui";

const chartColors = ["#397064", "#c49045", "#547894", "#8a655c", "#758469", "#7a6c91"];
const transactionLabels: Record<string, string> = { buy: "买入", sell: "卖出", subscribe: "申购", redeem: "赎回", dividend: "分红", fee: "费用", tax: "税费", adjustment: "调整" };

export function PortfolioPage({ searchTarget, settings, onSettingsChange }: { searchTarget?: SearchResult | null; settings: AppSettings; onSettingsChange: (settings: AppSettings) => void }) {
  const [snapshot, setSnapshot] = useState<PortfolioSnapshot>({ totalMarketValue: "0", totalCost: "0", unrealizedGain: "0", realizedGain: "0", holdings: [], updatedAt: null });
  const [accounts, setAccounts] = useState<InvestmentAccount[]>([]);
  const [instruments, setInstruments] = useState<Instrument[]>([]);
  const [transactions, setTransactions] = useState<PortfolioTransaction[]>([]);
  const [accountDraft, setAccountDraft] = useState<InvestmentAccount | null>(null);
  const [instrumentDraft, setInstrumentDraft] = useState<Instrument | null>(null);
  const [transactionDraft, setTransactionDraft] = useState<PortfolioTransaction | null>(null);
  const [error, setError] = useState<WorkbenchError | null>(null);
  const { busy, mutate } = useMutation(setError);
  const [notice, setNotice] = useState<string | null>(null);
  const [csvAccountId, setCsvAccountId] = useState<string | null>(null);
  const [transactionLimit, setTransactionLimit] = useState(12);
  const [refreshing, setRefreshing] = useState(false);
  const [valuationError, setValuationError] = useState<WorkbenchError | null>(null);
  const load = useCallback(async () => { try { const [valuation, accountData, instrumentData, transactionData] = await Promise.all([call<PortfolioSnapshot>("get_portfolio_snapshot").then((value) => ({ value, error: null })).catch((error: WorkbenchError) => ({ value: null, error })), call<InvestmentAccount[]>("list_investment_accounts"), call<Instrument[]>("list_instruments"), call<PortfolioTransaction[]>("list_portfolio_transactions")]); setAccounts(accountData); setInstruments(instrumentData); setTransactions(transactionData); setValuationError(valuation.error); if (valuation.value) setSnapshot(valuation.value); setError(valuation.error); } catch (value) { setError(value as WorkbenchError); } }, []);
  useEffect(() => { void load(); }, [load]);

  useSearchTarget(searchTarget, "instrument", instruments, setInstrumentDraft);
  const allocation = useMemo(() => snapshot.holdings.filter((holding) => Number(holding.marketValue) > 0).map((holding) => ({ name: holding.name, value: Number(holding.marketValue) })), [snapshot]);
  const columns = useMemo<ColumnDef<Holding>[]>(() => [
    { header: "资产", cell: ({ row }) => <div className="asset-cell"><strong>{row.original.name}</strong><small>{row.original.code}</small></div> },
    { header: "持有份额", accessorKey: "quantity", cell: ({ getValue }) => number(String(getValue()), 4) },
    { header: "平均成本", accessorKey: "averageCost", cell: ({ getValue }) => money(String(getValue()), settings.amountsHidden) },
    { header: "当前价格", cell: ({ row }) => <div>{row.original.priceSource === "missing" ? "未知" : money(row.original.currentPrice, settings.amountsHidden)}<small className="table-sub">{row.original.priceSource === "missing" ? "缺少价格" : row.original.priceSource === "tushare" ? "Tushare" : "手工"}</small></div> },
    { header: "市值", cell: ({ row }) => row.original.priceSource === "missing" && row.original.quantity !== "0" ? "未知" : money(row.original.marketValue, settings.amountsHidden) },
    { header: "浮动收益", cell: ({ row }) => <span className={Number(row.original.unrealizedGain) >= 0 ? "gain" : "loss"}>{row.original.priceSource === "missing" && row.original.quantity !== "0" ? "未知" : money(row.original.unrealizedGain, settings.amountsHidden)}</span> },
  ], [settings.amountsHidden]);
  const table = useReactTable({ data: snapshot.holdings, columns, getCoreRowModel: getCoreRowModel() });

  async function updateVisibility() { try { const updated = await call<AppSettings>("update_settings", { settings: { ...settings, amountsHidden: !settings.amountsHidden } }); onSettingsChange(updated); } catch (value) { setError(value as WorkbenchError); } }
  async function saveAccount() { if (!accountDraft) return; await mutate(async () => { await call("upsert_investment_account", { account: accountDraft }); setAccountDraft(null); await load(); }); }
  async function saveInstrument() { if (!instrumentDraft) return; await mutate(async () => { await call("upsert_instrument", { instrument: instrumentDraft }); setInstrumentDraft(null); await load(); }); }
  async function saveTransaction() { if (!transactionDraft) return; await mutate(async () => { await call("upsert_portfolio_transaction", { transaction: transactionDraft }); setTransactionDraft(null); await load(); }); }
  function newTransaction() { if (!accounts.length) { setAccountDraft(emptyAccount()); setNotice("请先建立一个投资账户"); return; } if (!instruments.length) { setInstrumentDraft(emptyInstrument()); setNotice("请先添加一项资产"); return; } setTransactionDraft({ ...emptyTransaction(), accountId: accounts[0].id, instrumentId: instruments[0].id }); }
  async function refreshQuotes() { setRefreshing(true); try { const report = await call<QuoteRefreshReport>("refresh_tushare_quotes"); setNotice(`行情更新完成：成功 ${report.updated}，失败 ${report.failed}${report.errors[0] ? ` · ${report.errors[0]}` : ""}`); await load(); } catch (value) { setError(value as WorkbenchError); } finally { setRefreshing(false); } }
  async function importCsv() { if (!csvAccountId) return; await mutate(async () => { const path = await open({ multiple: false, filters: [{ name: "CSV", extensions: ["csv"] }] }); if (!path) return; const report = await call<ImportReport>("import_portfolio_csv", { path, accountId: csvAccountId }); setCsvAccountId(null); setNotice(`导入完成：成功 ${report.imported}，跳过 ${report.skipped}${report.errors[0] ? ` · ${report.errors[0]}` : ""}`); await load(); }); }
  async function exportTemplate() { try { const path = await save({ defaultPath: "投资交易导入模板.csv", filters: [{ name: "CSV", extensions: ["csv"] }] }); if (!path) return; await call("export_portfolio_csv_template", { path }); setNotice("CSV 模板已保存"); } catch (value) { setError(new WorkbenchError(value)); } }

  return <div className="page portfolio-page">
    {error && <ErrorBanner message={error.message} recovery={error.recovery} onDismiss={() => setError(null)} />}
    {notice && <div className="notice-banner"><CircleDollarSign size={17} />{notice}<button onClick={() => setNotice(null)}>×</button></div>}
    <div className="page-heading"><div><span className="eyebrow">KNOW WHAT YOU OWN</span><h1>投资组合</h1><p>记录资产、成本与决策，只做分析，不连接券商、不执行交易。</p></div><div className="heading-actions"><Button variant="secondary" onClick={() => { if (!accounts.length) { setNotice("请先建立投资账户"); return; } setCsvAccountId(accounts[0].id); }}><FileInput size={16} />导入 CSV</Button><Button variant="secondary" onClick={() => void refreshQuotes()} disabled={!settings.quoteEnabled || refreshing}><RefreshCw size={16} className={refreshing ? "spin" : ""} />{refreshing ? "更新中" : "更新行情"}</Button><Button onClick={newTransaction}><Plus size={16} />记一笔</Button></div></div>
    {valuationError && <div className="notice-banner">估值暂不可用。账户、资产和历史交易仍可编辑；下方旧汇总不能作为当前估值。</div>}
    {snapshot.valuationComplete === false && <div className="notice-banner">{snapshot.missingPriceCount} 项持仓缺少价格，市值和浮动收益仅包含可估值部分。请补录手工价格。</div>}
    <div className="portfolio-overview">
      <Card className="portfolio-total"><div className="metric-label"><span>{snapshot.valuationComplete === false ? "已知价格的市值小计" : "当前总市值"}</span><button onClick={() => void updateVisibility()}>{settings.amountsHidden ? <EyeOff size={17} /> : <Eye size={17} />}</button></div><strong>{valuationError ? "暂不可用" : money(snapshot.totalMarketValue, settings.amountsHidden)}</strong><div className="portfolio-deltas"><span className={Number(snapshot.unrealizedGain) >= 0 ? "gain" : "loss"}>{Number(snapshot.unrealizedGain) >= 0 ? <TrendingUp size={15} /> : <TrendingDown size={15} />}{snapshot.valuationComplete === false ? "浮动收益不完整" : `浮动 ${money(snapshot.unrealizedGain, settings.amountsHidden)}`}</span><span>已实现 {money(snapshot.realizedGain, settings.amountsHidden)}</span></div><small>{snapshot.updatedAt ? `价格更新至 ${snapshot.updatedAt}` : "尚无行情记录"}</small></Card>
      <Card><span className="card-kicker">持仓成本</span><h3>{money(snapshot.totalCost, settings.amountsHidden)}</h3><small>{snapshot.holdings.length} 项持仓</small></Card>
      <Card><span className="card-kicker">投资账户</span><h3>{accounts.length}</h3><button className="text-link" onClick={() => setAccountDraft(emptyAccount())}>管理账户</button></Card>
      <Card><span className="card-kicker">行情状态</span><h3>{settings.quoteEnabled ? "已启用" : "本地模式"}</h3><small>{settings.quoteEnabled ? "仅向 Tushare 发送证券代码" : "只使用手工价格"}</small></Card>
    </div>
    <div className="portfolio-grid">
      <Card className="allocation-card"><SectionHeader title="资产配置" description={snapshot.valuationComplete === false ? "仅按有价格的持仓计算，不代表完整配置" : "按当前市值计算"} />{allocation.length ? <div className="allocation-chart"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={allocation} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={3}>{allocation.map((_, index) => <Cell key={index} fill={chartColors[index % chartColors.length]} />)}</Pie><Tooltip formatter={(value) => money(Number(value), settings.amountsHidden)} /></PieChart></ResponsiveContainer><div className="allocation-legend">{allocation.slice(0, 6).map((item, index) => <div key={item.name}><span style={{ background: chartColors[index % chartColors.length] }} /><strong>{item.name}</strong><small>{money(item.value, settings.amountsHidden)}</small></div>)}</div></div> : <EmptyState compact title="暂无资产配置" detail="添加资产并记录一笔买入。" />}</Card>
      <Card className="account-list-card"><SectionHeader title="账户" action={<Button size="sm" variant="secondary" onClick={() => setAccountDraft(emptyAccount())}><Plus size={14} />账户</Button>} /><div className="account-list">{accounts.map((account) => <button key={account.id} onClick={() => setAccountDraft(account)}><span className="account-icon"><Landmark size={17} /></span><div><strong>{account.name}</strong><small>{account.kind === "securities" ? "证券账户" : account.kind === "fund" ? "基金账户" : "现金账户"}</small></div><Badge tone="neutral">{account.currency}</Badge></button>)}{accounts.length === 0 && <EmptyState compact title="尚未建立账户" detail="例如主证券账户或基金账户。" />}</div></Card>
    </div>
    <Card className="holding-table-card"><SectionHeader title="当前持仓" description="精确十进制计算移动加权平均成本" action={<div className="inline-actions"><Button size="sm" variant="secondary" onClick={() => setInstrumentDraft(emptyInstrument())}><Plus size={14} />资产</Button><Button size="sm" variant="ghost" onClick={() => void exportTemplate()}><FileDown size={14} />CSV 模板</Button></div>} />{snapshot.holdings.length ? <div className="data-table-wrap"><table className="data-table"><thead>{table.getHeaderGroups().map((group) => <tr key={group.id}>{group.headers.map((header) => <th key={header.id}>{header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map((row) => <tr key={row.id} onDoubleClick={() => setInstrumentDraft(instruments.find((item) => item.id === row.original.instrumentId) ?? null)}>{row.getVisibleCells().map((cell) => <td key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div> : <EmptyState title="还没有持仓" detail="先添加证券或基金，再记录买入、申购或资金调整。" action={<Button onClick={() => setInstrumentDraft(emptyInstrument())}>添加第一项资产</Button>} />}</Card>
    <Card className="transaction-card"><SectionHeader title="最近交易" description="双击持仓可更新手工价格" action={<Button size="sm" onClick={newTransaction}><Plus size={14} />交易</Button>} />{transactions.length ? <div className="transaction-list">{transactions.slice(0, transactionLimit).map((transaction) => { const instrument = instruments.find((item) => item.id === transaction.instrumentId); const displayAmount = transaction.amount === "0" ? multiplyDecimals(transaction.quantity, transaction.unitPrice) : transaction.amount; return <button key={transaction.id} onClick={() => setTransactionDraft(transaction)}><span className={`transaction-type ${["sell", "redeem"].includes(transaction.kind) ? "out" : "in"}`}>{transactionLabels[transaction.kind]}</span><div><strong>{instrument?.name ?? "未知资产"}</strong><small>{transaction.tradeDate} · {number(transaction.quantity, 4)} 份</small></div><span>{money(displayAmount, settings.amountsHidden)}</span></button>; })}</div> : <EmptyState compact title="暂无交易记录" detail="每一笔数据都只保存在本机。" />}</Card>

    {transactions.length > transactionLimit && <Button variant="ghost" onClick={() => setTransactionLimit((value) => value + 30)}>显示更多交易</Button>}
    <Modal busy={busy} error={error} open={csvAccountId !== null} onClose={() => setCsvAccountId(null)} title="导入交易 CSV" footer={<><Button variant="secondary" onClick={() => setCsvAccountId(null)}>取消</Button><Button onClick={() => void importCsv()}>选择 CSV 文件并导入</Button></>}>
      <Field label="导入到哪个账户" hint="整份文件的交易均归入此账户，请先确认。"><Select value={csvAccountId ?? ""} onChange={(event) => setCsvAccountId(event.currentTarget.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</Select></Field>
    </Modal>
    <Modal busy={busy} error={error} open={Boolean(accountDraft)} onClose={() => setAccountDraft(null)} title={accountDraft?.id ? "编辑账户" : "新建账户"} footer={<><Button variant="secondary" onClick={() => setAccountDraft(null)}>取消</Button><Button onClick={() => void saveAccount()}>保存账户</Button></>}>
      {accountDraft && <div className="form-grid"><Field label="账户名称" className="span-2"><Input autoFocus value={accountDraft.name} onChange={(event) => setAccountDraft({ ...accountDraft, name: event.currentTarget.value })} placeholder="例如：主证券账户" /></Field><Field label="账户类型"><Select value={accountDraft.kind} onChange={(event) => setAccountDraft({ ...accountDraft, kind: event.currentTarget.value as InvestmentAccount["kind"] })}><option value="securities">证券账户</option><option value="fund">基金账户</option><option value="cash">现金账户</option></Select></Field><Field label="基础货币"><Select value={accountDraft.currency} onChange={(event) => setAccountDraft({ ...accountDraft, currency: event.currentTarget.value })}><option value="CNY">人民币 CNY</option></Select></Field></div>}
    </Modal>
    <Modal busy={busy} error={error} open={Boolean(instrumentDraft)} onClose={() => setInstrumentDraft(null)} title={instrumentDraft?.id ? "编辑资产" : "添加资产"} footer={<><Button variant="secondary" onClick={() => setInstrumentDraft(null)}>取消</Button><Button onClick={() => void saveInstrument()}>保存资产</Button></>}>
      {instrumentDraft && <div className="form-grid"><Field label="证券代码"><Input autoFocus value={instrumentDraft.code} onChange={(event) => setInstrumentDraft({ ...instrumentDraft, code: event.currentTarget.value })} placeholder="例如 510300" /></Field><Field label="名称"><Input value={instrumentDraft.name} onChange={(event) => setInstrumentDraft({ ...instrumentDraft, name: event.currentTarget.value })} placeholder="例如 沪深300ETF" /></Field><Field label="资产类型"><Select value={instrumentDraft.kind} onChange={(event) => setInstrumentDraft({ ...instrumentDraft, kind: event.currentTarget.value as Instrument["kind"] })}><option value="stock">A 股</option><option value="etf">ETF</option><option value="fund">公募基金</option><option value="cash">现金</option></Select></Field><Field label="手工价格" hint="修改后记录今日价格；清空不删除已有价格历史"><Input inputMode="decimal" value={instrumentDraft.manualPrice ?? ""} onChange={(event) => setInstrumentDraft({ ...instrumentDraft, manualPrice: event.currentTarget.value || null })} placeholder="无行情时使用" /></Field><Field label="市场"><Select value={instrumentDraft.market} onChange={(event) => setInstrumentDraft({ ...instrumentDraft, market: event.currentTarget.value })}><option value="CN">中国内地</option></Select></Field><Field label="货币"><Select value={instrumentDraft.currency} onChange={(event) => setInstrumentDraft({ ...instrumentDraft, currency: event.currentTarget.value })}><option value="CNY">人民币 CNY</option></Select></Field></div>}
    </Modal>
    <Modal busy={busy} error={error} open={Boolean(transactionDraft)} onClose={() => setTransactionDraft(null)} title={transactionDraft?.id ? "编辑交易" : "记录交易"} size="lg" footer={<>{transactionDraft?.id && <Button variant="danger" onClick={() => { if (window.confirm("删除此交易？剩余交易序列仍须保持有效，删除后重新计算持仓。")) void mutate(async () => { await call("delete_record", { kind: "transaction", id: transactionDraft.id }); setTransactionDraft(null); await load(); }); }}>删除交易</Button>}<Button variant="secondary" onClick={() => setTransactionDraft(null)}>取消</Button><Button onClick={() => void saveTransaction()}>保存交易</Button></>}>
      {transactionDraft && <div className="form-grid"><Field label="账户"><Select value={transactionDraft.accountId} onChange={(event) => setTransactionDraft({ ...transactionDraft, accountId: event.currentTarget.value })}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</Select></Field><Field label="资产"><Select value={transactionDraft.instrumentId} onChange={(event) => setTransactionDraft({ ...transactionDraft, instrumentId: event.currentTarget.value })}>{instruments.map((instrument) => <option key={instrument.id} value={instrument.id}>{instrument.code} · {instrument.name}</option>)}</Select></Field><Field label="交易类型"><Select value={transactionDraft.kind} onChange={(event) => setTransactionDraft({ ...transactionDraft, kind: event.currentTarget.value as PortfolioTransaction["kind"] })}>{Object.entries(transactionLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</Select></Field><Field label="日期"><Input type="date" value={transactionDraft.tradeDate} onChange={(event) => setTransactionDraft({ ...transactionDraft, tradeDate: event.currentTarget.value })} /></Field><Field label="数量 / 份额"><Input inputMode="decimal" value={transactionDraft.quantity} onChange={(event) => setTransactionDraft({ ...transactionDraft, quantity: event.currentTarget.value })} /></Field><Field label="单价 / 净值"><Input inputMode="decimal" value={transactionDraft.unitPrice} onChange={(event) => setTransactionDraft({ ...transactionDraft, unitPrice: event.currentTarget.value })} /></Field><Field label="成交金额" hint={transactionDraft.kind === "adjustment" ? "现金调整：正数入账，负数出账；不允许透支" : "填 0 时按数量 × 单价计算"}><Input inputMode="decimal" value={transactionDraft.amount} onChange={(event) => setTransactionDraft({ ...transactionDraft, amount: event.currentTarget.value })} /></Field><Field label="手续费"><Input inputMode="decimal" value={transactionDraft.fee} onChange={(event) => setTransactionDraft({ ...transactionDraft, fee: event.currentTarget.value })} /></Field><Field label="税费"><Input inputMode="decimal" value={transactionDraft.tax} onChange={(event) => setTransactionDraft({ ...transactionDraft, tax: event.currentTarget.value })} /></Field><Field label="备注" className="span-2"><Textarea rows={4} value={transactionDraft.notes} onChange={(event) => setTransactionDraft({ ...transactionDraft, notes: event.currentTarget.value })} /></Field></div>}
    </Modal>
  </div>;
}
